import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
      className="dark"
      style={{
        colorScheme: "dark",
      }}
    >
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex w-full h-screen flex-col">
            <Navbar />
            {/* <Separator /> */}
            <section className="flex flex-grow max-w-7xl mx-auto py-5 px-5 w-full">
              {children}
            </section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
